name: Build Android Kernel

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            gcc-aarch64-linux-gnu \
            git make bc flex bison \
            libssl-dev libncurses5-dev \
            libelf-dev zlib1g-dev \
            python3 \
            wget

          # Build and install older dtc (1.4.7) from source
          wget https://git.kernel.org/pub/scm/utils/dtc/dtc.git/snapshot/dtc-1.4.7.tar.gz
          tar xzf dtc-1.4.7.tar.gz
          cd dtc-1.4.7
          make -j$(nproc)
          sudo make install PREFIX=/usr
          cd ..
          rm -rf dtc-1.4.7*

      - name: Set up environment
        run: |
          echo "ARCH=arm64" >> $GITHUB_ENV
          echo "CROSS_COMPILE=aarch64-linux-gnu-" >> $GITHUB_ENV
          echo "DTC=dtc" >> $GITHUB_ENV
          echo "DTC_FLAGS=-Wno-error -@" >> $GITHUB_ENV

      - name: Patch build system
        run: |
          # Disable problematic DTC checks
          sed -i 's/-Werror//g' scripts/Makefile.lib
          sed -i 's/^\(dtc_cpp_flags.*=.*\)/\1 -Wno-error/' scripts/Makefile.lib

      - name: Configure kernel
        run: |
          make ARCH=arm64 m10lte_swa_open_defconfig
          yes "" | make ARCH=arm64 oldconfig

      - name: Build kernel
        run: |
          make ARCH=arm64 \
               DTC_EXT=dtc \
               DTC_FLAGS="-Wno-error -@" \
               -j$(nproc)

      - name: Verify build
        run: |
          ls -la arch/arm64/boot/
          [ -f arch/arm64/boot/Image ] || exit 1

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-build
          path: |
            arch/arm64/boot/Image
            arch/arm64/boot/dts/*.dtb
