name: Build Android Kernel

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            device-tree-compiler \
            gcc-aarch64-linux-gnu \
            git \
            make \
            bc \
            flex \
            bison \
            libssl-dev \
            libncurses5-dev \
            libelf-dev \
            zlib1g-dev \
            python3 \
            gcc-9 g++-9  # Use older GCC to avoid dtc issues

      - name: Set up environment
        run: |
          echo "ARCH=arm64" >> $GITHUB_ENV
          echo "CROSS_COMPILE=aarch64-linux-gnu-" >> $GITHUB_ENV
          echo "ANDROID_MAJOR_VERSION=q" >> $GITHUB_ENV
          echo "PLATFORM_VERSION=10" >> $GITHUB_ENV
          echo "CONFIG_SECTION_MISMATCH_WARN_ONLY=y" >> $GITHUB_ENV
          echo "CC=gcc-9" >> $GITHUB_ENV  # Use GCC 9 specifically
          echo "HOSTCC=gcc-9" >> $GITHUB_ENV

      - name: Initialize configuration
        run: |
          # Clean any previous builds
          make ARCH=arm64 distclean || true
          
          # Generate configuration
          make ARCH=arm64 m10lte_swa_open_defconfig
          yes "" | make ARCH=arm64 oldconfig

      - name: Apply dtc workaround
        run: |
          # Workaround for dtc multiple definition error
          sed -i 's/^YYLTYPE yylloc;/extern YYLTYPE yylloc;/' scripts/dtc/dtc-lexer.lex.c

      - name: Build kernel
        run: |
          make ARCH=arm64 -j$(nproc)

      - name: Verify artifacts
        run: |
          ls -la arch/arm64/boot/
          [ -f arch/arm64/boot/Image ] && echo "Kernel image found" || echo "Kernel image missing"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-artifacts
          path: |
            arch/arm64/boot/Image*
            .config
          if-no-files-found: error
