name: Build Android Kernel

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            device-tree-compiler \
            gcc-aarch64-linux-gnu \
            git \
            make \
            bc \
            flex \
            bison \
            libssl-dev \
            libncurses5-dev \
            libelf-dev \
            libssl-dev \
            zlib1g-dev

      - name: Set up environment variables
        run: |
          echo "ARCH=arm64" >> $GITHUB_ENV
          echo "PLATFORM_VERSION=10" >> $GITHUB_ENV
          echo "ANDROID_MAJOR_VERSION=q" >> $GITHUB_ENV
          echo "CONFIG_SECTION_MISMATCH_WARN_ONLY=y" >> $GITHUB_ENV

      - name: Configure kernel
        run: |
          make $CONFIG_SECTION_MISMATCH_WARN_ONLY ARCH=$ARCH m10lte_swa_open_defconfig

      - name: Build the kernel
        run: |
          make $CONFIG_SECTION_MISMATCH_WARN_ONLY ARCH=$ARCH -j$(nproc)

      - name: Create release artifact
        uses: actions/upload-artifact@v3
        with:
          name: kernel-image
          path: arch/arm64/boot/Image
