name: Kernel Build

on:
  push:
    branches: [ main ] 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v3

    - name: Set up build environment
      run: |
        sudo apt update
        sudo apt install -y bc bison flex libssl-dev make libc6-dev libncurses5-dev \
                            crossbuild-essential-arm64 git wget build-essential curl lz4 cpio

    - name: Clone toolchain (GCC)
      run: |
        git clone --depth=1 https://github.com/arter97/arm64-gcc.git gcc64

    - name: Build Kernel
      run: |
        export ARCH=arm64
        export SUBARCH=arm64
        export CROSS_COMPILE=$GITHUB_WORKSPACE/gcc64/bin/aarch64-linux-gnu-
        make m10lte_swa_open_defconfig
        make -j$(nproc)

    - name: Upload Kernel Image
      uses: actions/upload-artifact@v3
      with:
        name: kernel-out
        path: arch/arm64/boot/Image.gz-dtb
