name: Build Android Kernel

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            gcc-aarch64-linux-gnu \
            git make bc flex bison \
            libssl-dev libncurses5-dev \
            libelf-dev zlib1g-dev \
            gcc-10 g++-10  # Using GCC 10 instead of 9

      - name: Set up environment
        run: |
          echo "ARCH=arm64" >> $GITHUB_ENV
          echo "CROSS_COMPILE=aarch64-linux-gnu-" >> $GITHUB_ENV
          echo "CC=aarch64-linux-gnu-gcc" >> $GITHUB_ENV  # Use cross-compiler
          echo "HOSTCC=gcc-10" >> $GITHUB_ENV  # Host tools use GCC 10

      - name: Apply DTC fix
        run: |
          # Apply workaround for DTC multiple definition error
          sed -i 's/^YYLTYPE yylloc;/extern YYLTYPE yylloc;/' scripts/dtc/dtc-lexer.lex.c_shipped || true

      - name: Configure kernel
        run: |
          make ARCH=arm64 m10lte_swa_open_defconfig
          yes "" | make ARCH=arm64 oldconfig

      - name: Build kernel
        run: |
          make ARCH=arm64 \
               CC="$CROSS_COMPILE"gcc \
               HOSTCC=gcc-10 \
               DTC_FLAGS="-Wno-error" \
               -j$(nproc)

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-image
          path: arch/arm64/boot/Image*
