name: Build Android Kernel

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full history for version detection

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            device-tree-compiler \
            gcc-aarch64-linux-gnu \
            git \
            make \
            bc \
            flex \
            bison \
            libssl-dev \
            libncurses5-dev \
            libelf-dev \
            zlib1g-dev

      - name: Set up environment variables
        run: |
          echo "ARCH=arm64" >> $GITHUB_ENV
          echo "CROSS_COMPILE=aarch64-linux-gnu-" >> $GITHUB_ENV
          echo "ANDROID_MAJOR_VERSION=q" >> $GITHUB_ENV
          echo "PLATFORM_VERSION=10" >> $GITHUB_ENV
          echo "CONFIG_SECTION_MISMATCH_WARN_ONLY=y" >> $GITHUB_ENV

      - name: Clean previous build
        run: make clean || true

      - name: Configure kernel
        run: |
          make ARCH=${{ env.ARCH }} ${{ env.CONFIG_SECTION_MISMATCH_WARN_ONLY }} m10lte_swa_open_defconfig
          make ARCH=${{ env.ARCH }} oldconfig

      - name: Build the kernel
        run: |
          make ARCH=${{ env.ARCH }} -j$(nproc)

      - name: Verify build output
        run: |
          ls -la arch/arm64/boot/
          file arch/arm64/boot/Image*

      - name: Upload kernel image
        uses: actions/upload-artifact@v4
        with:
          name: kernel-image
          path: arch/arm64/boot/Image*
          if-no-files-found: error
