name: Build Android Kernel

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            gcc-aarch64-linux-gnu \
            git make bc flex bison \
            libssl-dev libncurses5-dev \
            libelf-dev zlib1g-dev \
            python3 \
            gcc-9 g++-9

          # Build and install compatible dtc
          wget https://git.kernel.org/pub/scm/utils/dtc/dtc.git/snapshot/dtc-1.4.7.tar.gz
          tar xzf dtc-1.4.7.tar.gz
          cd dtc-1.4.7
          make -j$(nproc) NO_PYTHON=1
          sudo make install PREFIX=/usr
          cd ..

      - name: Apply critical fixes
        run: |
          # 1. Fix array bounds error in libfdt
          sed -i 's/fdth->name = cpu_to_fdt32(val)/memcpy(\&fdth->name, \&val, sizeof(fdt32_t))/g' libfdt/libfdt.h

          # 2. Fix DTC multiple definitions
          [ -f scripts/dtc/dtc-lexer.lex.c_shipped ] && \
            sed -i 's/^YYLTYPE yylloc;/extern YYLTYPE yylloc;/' scripts/dtc/dtc-lexer.lex.c_shipped

          # 3. Disable all problematic warnings
          find . -type f -name "Makefile*" -exec sed -i \
            -e 's/-Werror=array-bounds//g' \
            -e 's/-Werror=stringop-overflow//g' \
            -e 's/-Werror=restrict//g' \
            -e 's/-Werror//g' {} +

          # 4. Patch scripts/dtc specifically
          sed -i '/^hostprogs-y += dtc$/a HOSTCFLAGS_dtc += -Wno-error -fcommon' scripts/dtc/Makefile

      - name: Configure kernel
        run: |
          make ARCH=arm64 distclean
          make ARCH=arm64 m10lte_swa_open_defconfig
          yes "" | make ARCH=arm64 oldconfig

      - name: Build kernel
        run: |
          make ARCH=arm64 \
               CC="gcc-9 -fcommon" \
               HOSTCC="gcc-9 -fcommon" \
               DTC=dtc \
               KCFLAGS="-Wno-error -Wno-error=array-bounds -Wno-error=stringop-overflow" \
               -j$(nproc)

      - name: Verify build
        run: |
          [ -f arch/arm64/boot/Image ] || (echo "Build failed - Kernel image not found" && exit 1)
          echo "Kernel built successfully"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-image
          path: arch/arm64/boot/Image
