name: Build Android Kernel

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            gcc-aarch64-linux-gnu \
            git make bc flex bison \
            libssl-dev libncurses5-dev \
            libelf-dev zlib1g-dev \
            device-tree-compiler=1.6.0-1  # Install specific older dtc version

      - name: Set up environment
        run: |
          echo "ARCH=arm64" >> $GITHUB_ENV
          echo "CROSS_COMPILE=aarch64-linux-gnu-" >> $GITHUB_ENV
          echo "DTC=dtc" >> $GITHUB_ENV  # Explicitly use system dtc

      - name: Patch DTC checks
        run: |
          # Disable strict device tree checks
          sed -i 's/^\(dtc_flags.*=.*\)/\1 -Wno-unit_address_vs_reg/' scripts/Makefile.lib
          sed -i 's/^\(dtc_flags.*=.*\)/\1 -Wno-simple_bus_reg/' scripts/Makefile.lib
          sed -i 's/^\(dtc_flags.*=.*\)/\1 -Wno-unit_address_format/' scripts/Makefile.lib

      - name: Configure kernel
        run: |
          make ARCH=arm64 m10lte_swa_open_defconfig
          yes "" | make ARCH=arm64 oldconfig

      - name: Build kernel
        run: |
          make ARCH=arm64 \
               DTC_FLAGS="-Wno-error -@ -Wno-unit_address_vs_reg -Wno-simple_bus_reg -Wno-unit_address_format" \
               -j$(nproc)

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-image
          path: |
            arch/arm64/boot/Image*
            arch/arm64/boot/dts/*.dtb
