name: Build Android Kernel

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            gcc-aarch64-linux-gnu \
            git make bc flex bison \
            libssl-dev libncurses5-dev \
            libelf-dev zlib1g-dev \
            python3 \
            gcc-9 g++-9

      - name: Set up environment
        run: |
          echo "ARCH=arm64" >> $GITHUB_ENV
          echo "CROSS_COMPILE=aarch64-linux-gnu-" >> $GITHUB_ENV
          echo "CC=gcc-9" >> $GITHUB_ENV
          echo "HOSTCC=gcc-9" >> $GITHUB_ENV
          echo "KBUILD_BUILD_USER=github" >> $GITHUB_ENV
          echo "KBUILD_BUILD_HOST=actions" >> $GITHUB_ENV

      - name: Patch build system
        run: |
          # Disable array bounds warnings
          sed -i 's/-Werror=array-bounds//g' scripts/Makefile.extrawarn
          sed -i 's/-Werror//g' scripts/Makefile.extrawarn
          
          # Patch libfdt header
          sed -i 's/fdth->name = cpu_to_fdt32(val)/memcpy(\&fdth->name, \&val, sizeof(fdt32_t))/g' libfdt/libfdt.h || true

      - name: Configure kernel
        run: |
          make ARCH=arm64 m10lte_swa_open_defconfig
          yes "" | make ARCH=arm64 oldconfig

      - name: Build kernel
        run: |
          make ARCH=arm64 \
               CC=gcc-9 \
               HOSTCC=gcc-9 \
               KCFLAGS="-Wno-error=array-bounds -Wno-error" \
               -j$(nproc)

      - name: Verify build
        run: |
          ls -la arch/arm64/boot/
          [ -f arch/arm64/boot/Image ] || exit 1

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-build
          path: |
            arch/arm64/boot/Image
            arch/arm64/boot/dts/*.dtb
